### ISSUE TITLE
Need Help pls!

### ISSUE THREAD

**Issue by jegue** [dargmuesli/bottom-news#1]
do you know where i need to change to send a image as a gif?
i try te cli /image send, but only send a gif as a photo! I need to send as a gif so it will auto play!
thanks for any help!

**Comment by dargmuesli** [comment]
Unfortunately it is currently not possible to send auto-playing GIFs in WhatsApp and therefore Yowsup. I sincerely hope that the WhatsApp developers work on that feature though, as I really want it to get implemented as soon as possible! :)

**Comment by jegue** [comment]
thanks man! will kepp in touch!

**Comment by dargmuesli** [comment]
Just a small update: WhatsApp is now able to send and show GIFs!
But it needs in-depth changes in Yowsup to implement this for easy use.
